export enum StringTemplates {
  SCHEDULE_MANAGER_TITLE = 'SchMgrTitle',
  PUBLISH_ABORTED = 'SchMgrPublishAborted',
  PUBLISH_INFLIGHT = 'SchMgrPublishInflight',
  PUBLISH_FAILED_OTHER_UPDATE = 'SchMgrPublishFailedOtherUpdate',
  PUBLISH_FAILED = 'SchMgrPublishFailed',
  PUBLISH_FAILED_ACTIVITY = 'SchMgrPublishFailedActivity',
  PUBLISH_SUCCESS = 'SchMgrPublishSuccess',
  PUBLISH_BUTTON = 'SchMgrPublishButton',
  PUBLISH_DIALOG_TITLE = 'SchMgrPublishDialogTitle',
  PUBLISH_DIALOG_TEXT = 'SchMgrPublishDialogText',
  LOAD_FAILED_TITLE = 'SchMgrLoadFailedTitle',
  LOAD_FAILED_TEXT = 'SchMgrLoadFailedText',
  TAB_SCHEDULES = 'SchMgrTabSchedules',
  TAB_RULES = 'SchMgrTabRules',
  CREATE_SCHEDULE_BUTTON = 'SchMgrCreateScheduleButton',
  CREATE_RULE_BUTTON = 'SchMgrCreateRuleButton',
  STATUS_OPEN = 'SchMgrStatusOpen',
  STATUS_CLOSED = 'SchMgrStatusClosed',
  STATUS_PENDING = 'SchMgrStatusPending',
  COLUMN_NAME = 'SchMgrColumnName',
  COLUMN_STATUS = 'SchMgrColumnStatus',
  COLUMN_STATUS_ASOF = 'SchMgrColumnStatusAsOf',
  COLUMN_RULES = 'SchMgrColumnRules',
  COLUMN_TIMEZONE = 'SchMgrColumnTimeZone',
  COLUMN_MANUALLYCLOSED = 'SchMgrColumnManuallyClosed',
  COLUMN_TYPE = 'SchMgrColumnType',
  COLUMN_TIME = 'SchMgrColumnTime',
  COLUMN_DATE = 'SchMgrColumnDate',
  ANY_TIME = 'SchMgrAnyTime',
  ANY_DAY = 'SchMgrAnyDay',
  DATE_FROM = 'SchMgrDateFrom',
  DATE_UNTIL = 'SchMgrDateUntil',
  CLOSED_YES = 'SchMgrClosedYes',
  CLOSED_NO = 'SchMgrClosedNo',
}

export default {
  [StringTemplates.SCHEDULE_MANAGER_TITLE]: 'Schedule Manager',
  [StringTemplates.PUBLISH_ABORTED]: 'The schedule publish was aborted. Your changes may not have been saved.',
  [StringTemplates.PUBLISH_INFLIGHT]: 'Another schedule publish is in progress. Publishing now will overwrite other changes.',
  [StringTemplates.PUBLISH_FAILED_OTHER_UPDATE]: 'Schedule was updated by someone else and cannot be published. Please reload and try again.',
  [StringTemplates.PUBLISH_FAILED]: 'Schedule publish failed.',
  [StringTemplates.PUBLISH_FAILED_ACTIVITY]: 'Switch to a non-available activity to publish.',
  [StringTemplates.PUBLISH_SUCCESS]: 'Successfully published schedules.',
  [StringTemplates.PUBLISH_BUTTON]: 'Publish Schedules',
  [StringTemplates.PUBLISH_DIALOG_TITLE]: 'Publishing schedules',
  [StringTemplates.PUBLISH_DIALOG_TEXT]: 'This may take a few moments, please wait...',
  [StringTemplates.LOAD_FAILED_TITLE]: 'Failed to load schedules',
  [StringTemplates.LOAD_FAILED_TEXT]: 'Please reload and try again.',
  [StringTemplates.TAB_SCHEDULES]: 'Schedules',
  [StringTemplates.TAB_RULES]: 'Rules',
  [StringTemplates.CREATE_SCHEDULE_BUTTON]: 'Create Schedule',
  [StringTemplates.CREATE_RULE_BUTTON]: 'Create Rule',
  [StringTemplates.STATUS_OPEN]: 'Open',
  [StringTemplates.STATUS_CLOSED]: 'Closed',
  [StringTemplates.STATUS_PENDING]: 'Pending Publish',
  [StringTemplates.COLUMN_NAME]: 'Name',
  [StringTemplates.COLUMN_STATUS]: 'Status',
  [StringTemplates.COLUMN_STATUS_ASOF]: 'as of',
  [StringTemplates.COLUMN_RULES]: 'Rules',
  [StringTemplates.COLUMN_TIMEZONE]: 'Time zone',
  [StringTemplates.COLUMN_MANUALLYCLOSED]: 'Manually closed',
  [StringTemplates.COLUMN_TYPE]: 'Type',
  [StringTemplates.COLUMN_TIME]: 'Time',
  [StringTemplates.COLUMN_DATE]: 'Date',
  [StringTemplates.ANY_TIME]: 'any time',
  [StringTemplates.ANY_DAY]: 'any day',
  [StringTemplates.DATE_FROM]: 'from',
  [StringTemplates.DATE_UNTIL]: 'until',
  [StringTemplates.CLOSED_YES]: 'Yes',
  [StringTemplates.CLOSED_NO]: 'No',
};